-- Expand product info sections from 3 to 10.

ALTER TABLE products ADD COLUMN IF NOT EXISTS info_section4_title VARCHAR(120);
ALTER TABLE products ADD COLUMN IF NOT EXISTS info_section4_content VARCHAR(2000);
ALTER TABLE products ADD COLUMN IF NOT EXISTS info_section4_enabled BOOLEAN DEFAULT FALSE;

ALTER TABLE products ADD COLUMN IF NOT EXISTS info_section5_title VARCHAR(120);
ALTER TABLE products ADD COLUMN IF NOT EXISTS info_section5_content VARCHAR(2000);
ALTER TABLE products ADD COLUMN IF NOT EXISTS info_section5_enabled BOOLEAN DEFAULT FALSE;

ALTER TABLE products ADD COLUMN IF NOT EXISTS info_section6_title VARCHAR(120);
ALTER TABLE products ADD COLUMN IF NOT EXISTS info_section6_content VARCHAR(2000);
ALTER TABLE products ADD COLUMN IF NOT EXISTS info_section6_enabled BOOLEAN DEFAULT FALSE;

ALTER TABLE products ADD COLUMN IF NOT EXISTS info_section7_title VARCHAR(120);
ALTER TABLE products ADD COLUMN IF NOT EXISTS info_section7_content VARCHAR(2000);
ALTER TABLE products ADD COLUMN IF NOT EXISTS info_section7_enabled BOOLEAN DEFAULT FALSE;

ALTER TABLE products ADD COLUMN IF NOT EXISTS info_section8_title VARCHAR(120);
ALTER TABLE products ADD COLUMN IF NOT EXISTS info_section8_content VARCHAR(2000);
ALTER TABLE products ADD COLUMN IF NOT EXISTS info_section8_enabled BOOLEAN DEFAULT FALSE;

ALTER TABLE products ADD COLUMN IF NOT EXISTS info_section9_title VARCHAR(120);
ALTER TABLE products ADD COLUMN IF NOT EXISTS info_section9_content VARCHAR(2000);
ALTER TABLE products ADD COLUMN IF NOT EXISTS info_section9_enabled BOOLEAN DEFAULT FALSE;

ALTER TABLE products ADD COLUMN IF NOT EXISTS info_section10_title VARCHAR(120);
ALTER TABLE products ADD COLUMN IF NOT EXISTS info_section10_content VARCHAR(2000);
ALTER TABLE products ADD COLUMN IF NOT EXISTS info_section10_enabled BOOLEAN DEFAULT FALSE;
